#!/usr/bin/env python3
# Execution wrapper: keeps preregistered H9 logic in h9_shadow_full.py but fixes current-index resolution
# from disclosure security-code union to official KAP issuer membership -> equity ticker.
p='tools/h9_shadow_full.py'
s=open(p,encoding='utf-8').read()
old='''def current_xu100():\n    # Current KAP XU100 filter + broad window: every constituent is expected to have >=1 disclosure.\n    rows=collect_range(date(2026,1,1),date(2026,8,11),IDX,7); s=set()\n    for e in rows:\n        for c in codes(e.get('stockCodes')):\n            if re.fullmatch(r'[A-Z0-9]{3,6}',c):s.add(c)\n    return s\n'''
new='''def current_xu100():\n    # KAP index-filtered disclosures identify current constituent ISSUERS. stockCodes may also\n    # contain bonds/share classes, so resolve issuer title to official IGS equity stockCode.\n    rows=collect_range(date(2026,1,1),date(2026,8,11),IDX,7)\n    titles=sorted({str(e.get("kapTitle") or "").strip() for e in rows if str(e.get("kapTitle") or "").strip()})\n    req=urllib.request.Request(BASE+"/tr/api/company/items/IGS/A",headers={"User-Agent":"Mozilla/5.0","Accept":"application/json"})\n    with urllib.request.urlopen(req,timeout=60) as r: comps=json.loads(r.read().decode())\n    def norm(x):return re.sub(r"[^A-Z0-9]","",str(x).upper().replace("İ","I").replace("Ş","S").replace("Ğ","G").replace("Ü","U").replace("Ö","O").replace("Ç","C"))\n    by={norm(r.get("kapMemberTitle")):r for r in comps}\n    out=set(); unresolved=[]; multi=[]\n    preferred=["ISCTR","KRDMD"]\n    for title in titles:\n        rec=by.get(norm(title))\n        if not rec:\n            # conservative fallback: unique normalized containment match\n            cand=[r for r in comps if norm(title) and (norm(title) in norm(r.get("kapMemberTitle")) or norm(r.get("kapMemberTitle")) in norm(title))]\n            rec=cand[0] if len(cand)==1 else None\n        if not rec: unresolved.append(title); continue\n        cs=[c for c in codes(rec.get("stockCode")) if re.fullmatch(r"[A-Z0-9]{3,6}",c)]\n        if len(cs)==1: out.add(cs[0])\n        elif cs:\n            pick=next((x for x in preferred if x in cs),None)\n            if pick is None:\n                multi.append((title,cs)); continue\n            out.add(pick); multi.append((title,cs,pick))\n    print("INDEX_ISSUER_TITLES",len(titles),"RESOLVED_TICKERS",len(out),"UNRESOLVED",unresolved,"MULTI",multi,flush=True)\n    return out\n'''
if old not in s:raise SystemExit('expected current_xu100 block not found')
s=s.replace(old,new,1)
exec(compile(s,p,'exec'),{'__name__':'__main__','__file__':p})
